server:
  port: ${api.port.product-service}
  error:
    include-message: always
    include-binding-errors: always

spring:
  config:
    import: configserver:http://localhost:9999
  data:
    mongodb:
      port: ${mongodb.port}
      database: productdb
