server:
  port: ${api.port.product-service}
  error:
    include-message: always
    include-binding-errors: always

spring:
  config:
    import: configserver:http://${CONFIG_SERVER_HOSTNAME:localhost}:${CONFIG_SERVER_PORT:9999}
  data:
    mongodb:
      host: ${MONGO_HOSTNAME:localhost}
      port: ${MONGO_PORT:27017}
      database: productdb
  rabbitmq:
    host: ${RABBITMQ_HOSTNAME:localhost}
    port: ${RABBITMQ_PORT:5672}
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 10
        max-interval: 5000
        multiplier: 1.5
